### ISSUE TITLE
[PA Review] User Authentication

### ISSUE THREAD

**Issue by doahuang** [doahuang/Met#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
@doahuang let me know when you update your link to heroku on your wiki!

**Comment by doahuang** [comment]
updated! https://met-app.herokuapp.com/#/ @niartenyaw

**Comment by niartenyaw** [comment]
Nice work! See the bullets that haven't been checked below:

# User Auth

## Functionality

- [X] The main button with logo should link to `/`

### Before Login

- [X] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [X] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [X] Can sign up a user
- [X] Can sign in as a user
- [X] Can log out a user
- [X] Can't sign up with the same username/email
- [X] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [X] Should not be able to visit `/login` or `/signup`
- [X] Should be able to refresh the page and still be logged in


## Style

- [X] The site should look exactly like the actual site
- [X] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)

**Comment by doahuang** [comment]
@niartenyaw  Thank you, I fixed and patched, please review

**Comment by niartenyaw** [comment]
Awesome, looks good!
