### ISSUE TITLE
[PA Review] Spots

### ISSUE THREAD

**Issue by doahuang** [doahuang/Met#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by doahuang** [comment]
Please review @niartenyaw

**Comment by niartenyaw** [comment]
Awesome work!

- [x] Am I supposed to see a map when I create a spot?
- [x] When I create a spot, how am i supposed to supply an image? it's url?
