### ISSUE TITLE
[PA Review] Reviews

### ISSUE THREAD

**Issue by doahuang** [doahuang/Met#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by doahuang** [comment]
Please review @niartenyaw

**Comment by niartenyaw** [comment]
Nice!

- [x] On successful review submittal, clear out the form
